name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Lint
      run: |
        curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        make terraform_lint

    - name: Create test k3d cluster
      run: |
        curl https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
        make create_cluster

    - name: Run tests
      run: make test